services:
  backend:
    container_name: cvagg-backend
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - database
      - redis
    volumes:
      - ./backend:/app
      - ./assets:/app/assets

  nginx:
    container_name: cvagg-nginx
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  database:
    container_name: cvagg-postgres
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    container_name: cvagg-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
