// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asthmatick1dd0/CVagg/http/server"
	"github.com/asthmatick1dd0/CVagg/internal/modules/auth"
	"github.com/asthmatick1dd0/CVagg/internal/modules/dashboard"
	"github.com/asthmatick1dd0/CVagg/internal/modules/editor"
	"github.com/asthmatick1dd0/CVagg/internal/modules/editor/entity/about"
	"github.com/asthmatick1dd0/CVagg/internal/modules/editor/entity/custom"
	"github.com/asthmatick1dd0/CVagg/internal/modules/editor/entity/education"
	"github.com/asthmatick1dd0/CVagg/internal/modules/editor/entity/hard_skill"
	"github.com/asthmatick1dd0/CVagg/internal/modules/editor/entity/job_experience"
	"github.com/asthmatick1dd0/CVagg/internal/modules/editor/entity/personal_data"
	"github.com/asthmatick1dd0/CVagg/internal/modules/editor/entity/resume_item"
	"github.com/asthmatick1dd0/CVagg/internal/modules/user"
	"github.com/asthmatick1dd0/CVagg/pkg/helpers/cvagglog"
	"github.com/gofiber/fiber/v2"
	"github.com/google/wire"
	"github.com/spf13/viper"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func newApp(viperViper *viper.Viper, logger *cvagglog.Logger, db *gorm.DB) (App, func(), error) {
	repository := user.NewRepository(db, logger)
	service := auth.NewAuthService(repository)
	handler := auth.NewHandler(service)
	dashboardRepository := dashboard.NewRepository(db, logger)
	dashboardService := dashboard.NewDashboardService(dashboardRepository)
	dashboardHandler := dashboard.NewHandler(dashboardService)
	resume_itemRepository := resume_item.NewRepository(db, logger)
	job_experienceRepository := job_experience.NewRepository(db, logger)
	educationRepository := education.NewRepository(db, logger)
	hard_skillRepository := hard_skill.NewRepository(db, logger)
	aboutRepository := about.NewRepository(db, logger)
	customRepository := custom.NewRepository(db, logger)
	personal_dataRepository := personal_data.NewRepository(db, logger)
	editorService := editor.NewService(dashboardRepository, resume_itemRepository, job_experienceRepository, educationRepository, hard_skillRepository, aboutRepository, customRepository, personal_dataRepository)
	editorHandler := editor.NewHandler(editorService)
	app := server.NewServerHTTP(handler, dashboardHandler, editorHandler)
	mainApp, cleanup := provideApp(app)
	return mainApp, func() {
		cleanup()
	}, nil
}

// wire.go:

type App struct {
	Fiber *fiber.App
}

// Handlers
var HandlerSet = wire.NewSet(auth.NewHandler, dashboard.NewHandler, editor.NewHandler)

// Services
var ServiceSet = wire.NewSet(auth.NewAuthService, dashboard.NewDashboardService, editor.NewService)

// Repositories
var RepositorySet = wire.NewSet(user.NewRepository, dashboard.NewRepository, about.NewRepository, custom.NewRepository, education.NewRepository, hard_skill.NewRepository, job_experience.NewRepository, personal_data.NewRepository, resume_item.NewRepository)

// Server
var ServerSet = wire.NewSet(server.NewServerHTTP)

func provideApp(app *fiber.App) (App, func()) {
	cleanup := func() {
		app.Shutdown()
	}
	return App{Fiber: app}, cleanup
}
